spring:

  jpa:
    #    properties:
    #      javax:
    #        persistence:
    #          schema-generation:
    #            create-source: metadata
    #            scripts:
    #             action: create
    #             create-target: create.sql
      hibernate:
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
      database-platform: org.hibernate.dialect.H2Dialect
  datasource:
        url: jdbc:h2:~/test1
        username: admin
        password: admin
    #initialization-mode: always
    #platform: mysql
  jackson:
    serialization:
      write-dates-as-timestamps: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG